server:
  port: 9004
spring:
  application:
    name: eureka-feign-client

  zipkin:
    base-url: http://localhost:9010
  sleuth:
    sampler:
      percentage: 1.0


feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
