## 本地模式
spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native


# remote git 模式
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xionghao5/springcloud_learn
#          searchPaths: spring_cloud_config
#          username:
#          password:
#      label: main
#  application:
#    name: eureka-config-server

server:
  port: 9008
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/