eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9010
spring:
  application:
    name: eureka-zipkin-server

  sleuth:
    sampler:
      percentage: 1.0
    enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&useSSL=false
    username: root
    password: 1234

zipkin:
  storage:
    type: mysql
