server:
  port: 9991
spring:
  application:
    name: rocketmq-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rm-producer-group
