---
spring:
  profiles: peer1
server:
  port: 9000
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9001/eureka

---
spring:
  profiles: peer2
server:
  port: 9001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9000/eureka


