server:
  port: 9003
spring:
  application:
    name: eureka-ribbon-client

  zipkin:
    base-url: http://localhost:9010
  sleuth:
    sampler:
      percentage: 1.0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

management:
  security:
    enabled: false
